const FETCH_DEFAULT_LOCATION = 'FETCH_DEFAULT_LOCATION';
const FETCH_DEFAULT_LOCATION_FULFILLED = 'FETCH_DEFAULT_LOCATION_FULFILLED';
const MAP_SCRIPT_LOADED = 'MAP_SCRIPT_LOADED';

export {
  FETCH_DEFAULT_LOCATION,
  FETCH_DEFAULT_LOCATION_FULFILLED,
  MAP_SCRIPT_LOADED,
};
